Design/#3 메인페이지 퍼블리싱
CarrotAuction/frontend pull request #5
Opened 2023-11-08 06:11 UTC by Leeseunghwan7305

## 📖 개요
+ 메인페이지 퍼블리싱
## 💻 작업사항
+ intersection observer를 활용해 이미지 레이지 로딩 / 애니메이션 구현
+ banner / footer / introduce 컴포넌트 구현
+ 

-

## 💡 작성한 이슈 외에 작업한 사항
+ nav바에서 반응형으로 메뉴토글이 보여줘야하는데 useWindow훅 대신 css로 대체

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2023-11-08 20:37 UTC, Kimyebin00 requested changes
main / section / article 태그 사용해서 구현한 거 좋은 거 같아요. 냅다 div로 다 했었는데 저도 이제 이렇게 구현해보겠습니다. 빨리 구현하셨네용 수고하셨습니다!!

2023-11-08 20:37 UTC, Kimyebin00 commented on src/common/Nav/index.tsx
>      setToggle((pre) => !pre);
setToggle((pre) => !pre);
setToggle(!toggle);

두 코드의 사용 차이가 어떻게 돼요? 아래의 코드로만 작성했었는데, 이렇게 사용하는 건 처음 봐서요! 궁금합니다🙂

2023-11-08 20:37 UTC, Kimyebin00 commented on src/components/Banner/index.tsx
> +const Baneer = () => {
Baneer -> Banner

오타여~

2023-11-08 20:37 UTC, Kimyebin00 commented on src/constants/Banner.ts
나중에 코드 작성하시려고 만들어두신 걸까요? 아니면 삭제해주세용

2023-11-09 20:29 UTC, Leeseunghwan7305 commented on src/common/Nav/index.tsx
>      setToggle((pre) => !pre);
batch처리를 방지하려고 안에 콜백함수를 넣는거예요 !
좀 더 자세한 설명은 여기 유튜브에 설명이 잘되어있어서 링크 드릴게요 !🙂
https://www.youtube.com/watch?v=hSdVDBPTT0U&t=287s

2023-11-09 20:30 UTC, Leeseunghwan7305 commented on src/components/Banner/index.tsx
> +const Baneer = () => {
수정하겠습니다 !

2023-11-09 20:30 UTC, Leeseunghwan7305 commented on src/constants/Banner.ts
앗 넹

2023-11-10 18:35 UTC, Kimyebin00 approved these changes
수고하셨습니다!

2023-11-11 07:13 UTC, merged